services:
  personal-finance:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - personal-finance-db
    networks:
      - personal_finance_net
      - app-network
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    networks:
      - personal_finance_net

  # DB
  personal-finance-db:
    image: postgres:15
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - personal_finance_net
volumes:
  pgdata:

networks:
  personal_finance_net:
    driver: bridge
  app-network:
    external: true
