# Default Configuration
spring:
  application:
    name: personal-finance
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:personal_finance_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      # username: your-username
      # password: your-password
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

server:
  port: ${SERVER_PORT:8500}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
logging:
  level:
    org.springdoc: DEBUG

# Dev configurations
---
spring:
  application:
    name: personal-finance
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT_EXTERNAL:5432}/${POSTGRES_DB:personal_finance_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      # username: your-username
      # password: your-password
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
server:
    port: ${SERVER_PORT:8400}

eureka:
  client:
    enabled: false  # Disable Eureka in dev

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true