# Default Configuration
spring:
  application:
    name: PersonalFinancesService
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:personal_finance_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8500}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true


# Dev configurations
---
spring:
  application:
    name: PersonalFinancesService
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT_EXTERNAL:5432}/${POSTGRES_DB:personal_finance_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
    port: ${DEV_SERVER:8400}

eureka:
  client:
    enabled: false  # Disable Eureka in dev