spring:
  application:
    name: PersonalFinancesService

# Default Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true


# Dev configurations
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
server:
    port: ${SERVER_PORT:8500}