name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1:
      - name: Checkout code
        uses: actions/checkout@v4
      # Step 2:
      - name: Set up JDK 17
        uses: actions/setup-java@4
        with:
          java-version: '17'
          distribution: 'corretto'
      # Step 3:
      - name: Build with Maven
        run: mvn clean package -DSkipTests=false
      # Step 4:
      - name: Run tests
        run: mvn test
